"""empty message

Revision ID: 15dba6311b18
Revises: 2428ae529b4b
Create Date: 2016-01-05 20:50:38.761705

"""

# revision identifiers, used by Alembic.
revision = '15dba6311b18'
down_revision = '2428ae529b4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
