"""empty message

Revision ID: 2428ae529b4b
Revises: a261637dc9bb
Create Date: 2015-12-31 14:10:27.257865

"""

# revision identifiers, used by Alembic.
revision = '2428ae529b4b'
down_revision = 'a261637dc9bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
