"""empty message

Revision ID: 6e1f2aa791ee
Revises: 8942d89b1b0e
Create Date: 2016-01-09 13:12:46.242205

"""

# revision identifiers, used by Alembic.
revision = '6e1f2aa791ee'
down_revision = '8942d89b1b0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
