"""empty message

Revision ID: 8942d89b1b0e
Revises: 15dba6311b18
Create Date: 2016-01-06 18:50:08.310672

"""

# revision identifiers, used by Alembic.
revision = '8942d89b1b0e'
down_revision = '15dba6311b18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    ### end Alembic commands ###
