"""empty message

Revision ID: a261637dc9bb
Revises: None
Create Date: 2015-12-30 17:28:21.582321

"""

# revision identifiers, used by Alembic.
revision = 'a261637dc9bb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'author_id')
    op.drop_table('users')
    ### end Alembic commands ###
