"""empty message

Revision ID: bb9f4aba7446
Revises: 4e834606736b
Create Date: 2016-02-14 17:47:50.537395

"""

# revision identifiers, used by Alembic.
revision = 'bb9f4aba7446'
down_revision = '4e834606736b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    ### end Alembic commands ###
